name: Worker 1 - CI/CD

on:
  push:
    branches: [ master, main ]
    paths:
      - 'worker-1/**'
  workflow_dispatch:

env:
  DOCKER_IMAGE: andrirj/worker-1
  
jobs:
  build-and-deploy:
    runs-on: [self-hosted, Linux]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build and push Docker image
      run: |
        cd worker-1
        docker build -t $DOCKER_IMAGE:${{ github.sha }} .
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push $DOCKER_IMAGE:${{ github.sha }}
    
    - name: Deploy to Kubernetes
      run: |
        kubectl set image deployment/worker-1 worker-1=$DOCKER_IMAGE:${{ github.sha }}
